site_name: My Notes
site_url: https://emptyteeth.github.io/
site_description: my notes

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:
    scheme: slate
    primary: black
    accent: green
  features:
    - navigation.top
    # - header.autohide
    # - navigation.instant

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.emoji
  - meta
  - mdx_truly_sane_lists
  - toc:
      permalink: true

plugins:
  # - search
  - meta-descriptions
